### ISSUE TITLE
Kafka destination not working in the Docker image. 

### ISSUE THREAD

**Issue by kub1x** [balabit/syslog-ng-docker#26]
When trying to send logs into a kafka destination using this image like so:
```
destination d_kafka_os_t1x {
    channel {
        destination  {
            kafka(
                client-lib-dir("/usr/lib/syslog-ng/3.11/java-modules/")
                properties_file("/etc/syslog-ng/kafka.conf")
                topic("some_topic")
            );
        };
    };
};
```
I get the following error: 
```
syslog-ng_1      | syslog-ng: Error setting capabilities, capability management disabled; error='Operation not permitted'
syslog-ng_1      | [2017-09-05T10:58:32.347728] Error: org/apache/kafka/clients/producer/Callback;
syslog-ng_1      | java.lang.NoClassDefFoundError: org/apache/kafka/clients/producer/Callback
syslog-ng_1      |      at java.lang.Class.forName0(Native Method)
syslog-ng_1      |      at java.lang.Class.forName(Class.java:278)
syslog-ng_1      |      at org.syslog_ng.SyslogNgClassLoader.loadClass(SyslogNgClassLoader.java:67)
syslog-ng_1      | Caused by: java.lang.ClassNotFoundException: org.apache.kafka.clients.producer.Callback
syslog-ng_1      |      at java.net.URLClassLoader$1.run(URLClassLoader.java:359)
syslog-ng_1      |      at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
syslog-ng_1      |      at java.security.AccessController.doPrivileged(Native Method)
syslog-ng_1      |      at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
syslog-ng_1      |      at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
syslog-ng_1      |      at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
syslog-ng_1      |      at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
syslog-ng_1      |      ... 3 more
syslog-ng_1      | [2017-09-05T10:58:32.350135] Can't find class; class_name='org.syslog_ng.kafka.KafkaDestination'
syslog-ng_1      | [2017-09-05T10:58:32.350777] Error initializing message pipeline; plugin name='java', location='#buffer:2:3'
```
Just like in the following issue: https://github.com/balabit/syslog-ng/issues/1151, but with no success fixing it. I tried to find kafka jars in `/opt/kafka` and `/var/lib/kafka` to add them to `client-lib-dir` parameter, but none of those directories is present in the image. 

Is the image kafka-ready? If so, how should I confuigure the kafka destination? 
Thanks in advance

**Comment by czanik** [comment]
The syslog-ng Kafka driver uses the Apache Kafka libraries. While the image contains the syslog-ng Kafka driver, the Apache Kafka libraries are not included. See https://www.balabit.com/sites/default/files/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html-single/index.html#configuring-destinations-kafka where to get those and how to configure syslog-ng.

**Comment by kub1x** [comment]
Ok. I expected all the features to work as no such limits were mentioned in README, if I didn't miss something. I've seen the docs, but thought the files might be in the image hidden somewhere. Thanks for the clerification.
